### ISSUE TITLE
[invader-refactor] refactor script references too.

### ISSUE THREAD

**Issue by Vaporeon** [SnowyMouse/invader#148]
This will depend on #33.
This could be done by parsing the scenario script source data and changing any matching references. We can then recompile the scripts as needed.

**Comment by SnowyMouse** [comment]
While #33 was completed, 343 Industries changed the behavior of tool.exe so that script sources are no longer loaded from scenario tags but from data folders, and Invader had to follow suit.

Therefore, Invader cannot feasibly do this without editing the data folder, and that opens a massive can of worms I really don't want to deal with, as invader-refactor is only intended to refactor tag data, and extending this to data files is _extremely_ hacky.

Unfortunately, this means you will need to do a find-and-replace on your data folder using a text editor of some kind such as [Atom](https://atom.io/).

**Comment by SnowyMouse** [comment]
While #33 was completed, 343 Industries changed the behavior of tool.exe so that script sources are no longer loaded from scenario tags but from data folders, and Invader had to follow suit.

Thus Invader cannot feasibly do this without editing the data folder, and that opens a massive can of worms I really don't want to deal with, as invader-refactor is only intended to refactor tag data, and extending this to data files is _extremely_ hacky.

You'll need to use a text editor such as [Atom](https://atom.io/) instead.
