### ISSUE TITLE
Can't compile stock Halo Xbox campaign maps c10, c40 and d20 from extracted tags - invalid utf-8 sequence error

### ISSUE THREAD

**Issue by nor2101** [SnowyMouse/invader#225]
I'm using invader v0.52.2-win32 on Windows 10.

The tags were extracted from the maps through six-shooter from an original NTSC USA Xbox Halo copy (v1.2). I also tried with a Halo PAL (IT,SPA) Xbox copy and got the same result.

The process was: extracting tags (including non-multiplayer globals) with separate index file, running them through invader-bludgeon to fix invalid data and rebuilding them for Xbox NTSC through invader-build (all of this through six-shooter, but I tried running the command line directly as well). 

I also tried without bludgeoning them first, same outcome.

Other alterations on the tags were not performed.

Other maps from the campaign and multiplayer rebuild/recompile fine, and work on an Original Xbox after that, only these three throw this error on the scenario tag upon trying to build them:
```
Script compilation error: extracted.hsc:363:83: error: failed to decode token - invalid utf-8 sequence of 1 bytes from index 46
FATAL ERROR: Failed to compile scripts: tag data is invalid
...in levels\c10\c10.scenario
Failed to compile tag levels\c10\c10.scenario
Failed to compile the map.
tag data is invalid
```
I tried to build both from the scenario tag directly and from extracted script data with the according options.

What could be causing this issue?

**Comment by SnowyMouse** [comment]
The issue is because of the ellipsis characters (`…`) in the print statements.

These characters are not valid ASCII, but they are valid Windows-1252. It was likely what was used when making the original HSC, and it was probably copied from a document editor that converts `...` to `…` such as Microsoft Word.

It is worth noting that the game does not actually support 1252 properly anyway, so this would not actually work in-game and is actually not valid, but the game just ignores it. The parser I use expects UTF-8 (which ASCII is a subset of and what most text editors edit in anyway), and anything else throws an exception error due to safety reasons.

You can edit the script in your favorite text editor on the given line and character (`extracted.hsc:363:83` means line 363 in column 83) and replace this with a proper `...` or just comment out the print statement.

**Comment by Aerocatia** [comment]
Yeah, as said the stock scripts are unfortunately invalid.

The scripts can be automatically fixed with the following bash one liner (this needs `sponge` from `moreutils`).
```
find data -type f -name "*.hsc" -exec bash -c 'iconv -f WINDOWS-1252 -t ASCII//TRANSLIT "${1}" | sponge "${1}"' bash '{}' \;
```

If you don't have access to a bash shell, you can just use this fixed copy of the stock scripts here:
[gearbox_scripts_fixed.zip](https://github.com/SnowyMouse/invader/files/10549534/gearbox_scripts_fixed.zip)

**Comment by nor2101** [comment]
Thanks! I didn't notice this because my windows copy was not using utf-8 at a system-wide level. Now when I open the extracted.hsc with a text editor those characters appear as a question mark, so I can easily identify them. Before they appeared as "normal" three-dots and I wasn't understanding the issue.

Thank you both @SnowyMouse and @Aerocatia for help and for the Invader project, now I can finish my Halo xbox project 👍
