### ISSUE TITLE
[New feature] Implement bitmap extraction

### ISSUE THREAD

**Issue by Vaporeon** [SnowyMouse/invader#39]
It would be really handy if invader-bitmap could extract bitmap tags back to raw data, preferably in some a way where it could be recompiled into the exact same tag without modification while using the best source available.

This would be useful for both editing existing tags without worrying about changing sequences or re-encoding tags with lossless source data in them into lossless bitmap tags.

**Comment by Kavawuvi** [comment]
Doing this will require being able to decode DXT-compressed bitmaps (non-trivial). This is because the color plate data is unlikely to be present in ripped tags.

Also, in the rare case the bitmap doesn't correspond to the color plate data (such as if the tag was modified by a tool such as Mozzarilla), it should be possible to provide a flag that the user can use.

**Comment by SnowyMouse** [comment]
The new invader-recover tool extracts color plates. There's still no lossy option available, however, so I'm leaving the issue open.

**Comment by SnowyMouse** [comment]
The new invader-recover tool extracts color plates. There's still no lossy option available, though a tool like [last-resort](https://github.com/SnowyMouse/last-resort) may be a better tool to do this since this is pretty dirty.
